### ISSUE TITLE
"displayOnlyOnRain: true" shows first map image when mirror wakes up

### ISSUE THREAD

**Issue by fnsign** [jalibu/MMM-RAIN-MAP#11]
Platform (Hardware/OS):
RPi, Buster
Node version:
14.17.5
MagicMirror version:
2.16.0
Module version:
2.0.x
Description of the issue:
I use the module together with MMM-OpenWeatherForecast and MMM-PIR-Sensor and have set `displayOnlyOnRain: true` in the config.
After first boot of the mirror the map is NOT shown, when it does NOT rain (=correct behaviour).
When the mirror display turns off and later turns on again (MMM-PIR-Sensor), one of the first frames of the map is displayed. The map appears to be frozen, as it doesn't cycle through the other frames. If `displayOnlyOnRain: false` is set, then the map is displayed correctly and the map cycles normally after wake-up.
Apparently this is a display error of the map when the mirror is waking up and `displayOnlyOnRain: true` is set (and it doesn't rain). Instead of no map, it shows one still frame.
I couldn't test if the map is shown and cycling, when`displayOnlyOnRain: true` and it DOES rain (it didn't rain over the last few days).

**Comment by jalibu** [comment]
Hi @fnsign 
thank you for your feedback.
As there are hundreds of forked versions of MMM-PIR-Sensor, could you please tell me the exact repository and version of yours?

Thanks

**Comment by fnsign** [comment]
Sure, it's the original from Pavarotti https://github.com/paviro/MMM-PIR-Sensor

**Comment by fnsign** [comment]
> I couldn't test if the map is shown and cycling, whendisplayOnlyOnRain: true and it DOES rain (it didn't rain over the last few days).

I want to add following information (don't know if it is usefull):
As it started to rain today in my area the map is shown correctly and is cycling while `displayOnlyOnRain: true` is set (works as expected).

**Comment by jalibu** [comment]
hmm..
I can not reproduce this on my side.

Let‘s sum up this isse:
- [good] onlyDisplayOnRain stops the animation and hides the module if there is no rain
- [good] On rain, the module unhides itself and also starts animation (as expected)
- [bad] For any reason MMM-PIR-Sensor unhides the module when it triggers a user presence (of course without enabling the animation, as this requires an explicit call in the module)

On my mirror, the PIR module does not inactivate/activate any modules. Do you have some extra settings or additional modules running?

**Comment by fnsign** [comment]
For MMM-PIR-Sensor i have now special settings, it is configured with the sensorPin assignment and a powerSavingdelay of 90s.

What's worth mentioning is, that I use MMM-pages and MMM-page-inidicator (both the original forks). My issue could be related to these modules as your module (v 1.x) couldn't display the maps correctly, if the module was not placed on page 0 (the first page). Only ca. 3/4 of the image estate was displayed with a white bevel around have of the map. The map was displayed correctly, when it was placed on page 0.

Thus, I placed the module (old and new version) on page 0. Maybe there is an interference with MMM-pages?

**Comment by jalibu** [comment]
@fnsign 
aha!
I'll check MMM-Pages compatibility asap.
A quick check on https://github.com/edward-shen/MMM-pages/blob/master/MMM-pages.js lines 224-228 showed indications of the problem

**Comment by jalibu** [comment]
@fnsign bitte mal mit neustem Release testen. Hoffe das klappt so

**Comment by fnsign** [comment]
Super, es klappt! Ich konnte heute Nachmittag beide Szenarien testen (mit und ohne Regen) und in beiden verhält sich das Modul wie erwartet. Besten Dank für den schnellen fix!
