### ISSUE TITLE
Latest update w/ forecast breaks the module, no map at all shown

### ISSUE THREAD

**Issue by fnsign** [jalibu/MMM-RAIN-MAP#12]
I just installed the latest version and no map is displayed at all. It is just blanked. 
No matter if `displayOnlyOnRain:` is set true or false.

**Comment by jalibu** [comment]
🙈 that happens when you build and commit your changes between two calls...

**Comment by jalibu** [comment]
Sorry for the inconvenience. Before trying this again, let's do it professionally with pull request and testing (before release!). @fnsign could you please checkout branch fix/BlankMap and test it?

**Comment by fnsign** [comment]
No worries! I tested the PR on the fix/BlankMap branch and everything is fine now! The `displayOnlyOnRain:`property iworks correctly, too. Thanks for fixing!
