### ISSUE TITLE
Map Lat/Long wrong - showing west by 660km

### ISSUE THREAD

**Issue by jvdkieft** [jalibu/MMM-RAIN-MAP#19]
### MagicMirror Version

2.16.0

### Module Version

99ee2a51800ee8ee5fc7cf7c52509cbf15028bbc

### Description

I added my location - lat: 41.626656, lng: -93.712166, but the map is centered on around North Platte, NE, 660km west of me at around lat: 41.128838909088635, long: -100.76163495551675.

### Steps to reproduce

1. Start MMM.
2. Look at map.

### config.js

```javascript
{
			module: "MMM-RAIN-MAP",
			position: "top_center",
			config: {
				animationSpeedMs: 400,
				colorizeTime: true,
				defaultZoomLevel: 8,
				displayTime: true,
				displayTimeline: true,
				displayClockSymbol: true,
				displayOnlyOnRain: false,
				extraDelayLastFrameMs: 1000,
				extraDelayCurrentFrameMs: 3000,
				markers: [
					{ lat: 41.626656, lng: -93.712166, color: "red" }
				],
				mapPositions: [
					{ lat: 41.626656, lng: -93.712166, zoom: 7, loops: 1 }
				],
				mapUrl: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
				mapHeight: "480px",
				mapWidth: "100%",
				maxHistoryFrames: -1,
				maxForecastFrames: -1,
				substitudeModules: [],
				updateIntervalInSeconds: 300,
			}
		},
```

**Comment by jalibu** [comment]
Hi @jvdkieft,
please check your mapWidth setting. You must use px there. Percentages are not allowed.

If I change that value to "400px", the map is centered at Des Moines.

**Comment by jvdkieft** [comment]
Thanks, that fixed it.
