### ISSUE TITLE
Is there a way to bring back the zoom in/zoom out?

### ISSUE THREAD

**Issue by jvdkieft** [jalibu/MMM-RAIN-MAP#20]
I like the feature in the previous version where the map would zoom into a location for a few frames and then zoom back out. Can we get this back? I don't see a way to do it with the new config.

**Comment by jalibu** [comment]
just duplicate a position, change the toom level and the number of loops

**Comment by jalibu** [comment]
```
mapPositions: [
  { lat: 49.41, lng: 8.717, zoom: 9, loops: 1 },
 { lat: 49.41, lng: 8.717, zoom: 5, loops: 3 },
],
```
