### ISSUE TITLE
running on pi (electron) this module crashes mm

### ISSUE THREAD

**Issue by khassel** [jalibu/MMM-RAIN-MAP#25]
### Platform

Raspberry Pi OS

### Node.js Version

16 or 17

### MagicMirror Version

2.17.1 or 2.18.0

### Module Version

current `main` but also older versions

### Description

Running this module on the pi crashes the whole mm. I used the default config from the README.

When running with dev console I will get `failed to load resource net err_insufficient_resources 200` when loading the png files from the map. Some time after this the screen turns black or white and never comes back. The mm app is still running, there are no logs on server side.

For reproducing this fast you can increase `mapWidth:` to `"620px"`.

If I disable the module everything works fine.

I did some research concerning `net err_insufficient_resources` and this seems to be a restriction of chromium ([source](https://codereview.chromium.org/18541))

> Add a constraint on how many requests can be outstanding for any given render process (browser-side).

> Once the constraint is reached, subsequent requests will fail with net::ERR_INSUFFICIENT_RESOURCES.

> The bound is defined as "25 MB", which represents the amount of private bytes we expect  the pending requests to consume in the browser. This number translates into around 6000 typical requests.

I have no solution for this and my first question is if anyone can also reproduce this. It depends on the size of the map and the map url and the cycle count, which is clear because of the above mentioned download restriction.

### Expected behavior

see description

### Current behavior

see description

### Possible solution

see description

### Steps to reproduce

1. Start MM (with dev console if you want to catch such errors)
2. Mirror displays module infos
3. Wait for errors in the dev console or for getting a white or black screen

### Log

```shell
- no server logs
- in dev console as mentioned above `failed to load resource net err_insufficient_resources 200`
```

### config.js

```javascript
standard as in current README
```

### Additional info

electron v16.0.6 (v16 is current version in mm v2.18)

**Comment by khassel** [comment]
Forget the noise ... I should have erlier created this issue because now I found the solution. Its a problem of the `shm_size` of the docker container I'm running.

**Comment by jalibu** [comment]
Puh, zum Glück. Ich bin vor Schreck fast rückwärts vom Stuhl gekippt :-D

**Comment by khassel** [comment]
sorry, es ist aber komischerweise immer so - kaum hat man das Issue geschrieben findet man die Lösung. Dann ist es halt peinlich, weil man es wieder direkt schliessen muss, aber egal, vielleicht hilft es irgendwann jemand anderem ...
