### ISSUE TITLE
Map showing nothing

### ISSUE THREAD

**Issue by Nneuland** [jalibu/MMM-RAIN-MAP#29]
### Platform

Raspbian GNU/Linux 11 (bullseye)

### Node.js Version

v16.15.0

### MagicMirror Version

2.19.0

### Module Version

0fea49e603e3637aa7052ee8f2a982a944b57583

### Description

My RAIN-MAP is running fine through MMM-remotecontrol, but the mirror itself is showing only a white box where the module should be.  

### Expected behavior

I should see a map of my region with rain coverage

### Current behavior

I am seeing only a while box with occasional radar information.  90-95% white

### Steps to reproduce

Fresh install of mm and the module

### Log

```shell
how do i get logs?
```

### config.js

```javascript
{
			module: "MMM-RAIN-MAP",
			position: "top_bar",
			disabled: false,
			config: {
				animationSpeedMs: 400,
			colorScheme: 2,
				colorizeTime: true,
				defaultZoomLevel: 8,
				displayTime: true,
				displayTimeline: true,
				displayClockSymbol: true,
				displayOnlyOnRain: false,
				extraDelayLastFrameMs: 1000,
				extraDelayCurrentFrameMs: 3000,
				markers: [
					{ lat: 48.856, lng: 2.35, color: "green" },
					{ lat: 48.856, lng: 2.35, color: "green" },
				],
				mapPositions: [
					{ lat: xxxxx, lng: -xxxxxx, zoom: 9, loops: 1 },
					{ lat: xxxxxx, lng: -xxxxxx, zoom: 6, loops: 1 },
				],
				mapUrl: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
				mapHeight: "125px", // must be a pixel value (no percent)
				mapWidth: "950px", // must be a pixel value (no percent)
				maxHistoryFrames: -1,
				maxForecastFrames: -1,
				substitudeModules: [],
				updateIntervalInSeconds: 300,
			}
```

### Additional info

I am uncertain how to replicate.  Has this been an issue for anyone else?

**Comment by jalibu** [comment]
Hi,
this is a known problem with the configured tileserver in older versions.
Please update to the latest module version and remove the mapUrl property in your config.

**Comment by Nneuland** [comment]
SOLVED!  Thank you so much.  Love this module

**Comment by jalibu** [comment]
> SOLVED! Thank you so much. Love this module

http://paypal.me/jalibu ;-)
