### ISSUE TITLE
Alternative MapUrl not longer supported

### ISSUE THREAD

**Issue by Rene1695** [jalibu/MMM-RAIN-MAP#33]
### Platform

Unraid

### Node.js Version

12.22.12

### MagicMirror Version

2.20.0

### Module Version

2.7.0 (#32)

### Description

Hey,

it seems like that the alternative MapUrl is no longer supported (the map without colors). Since i dont understand how the map URL is working in general, it would like to ask kindly, on an alternative map URL with no colors e.g. a dark mode version like this:

https://umap.openstreetmap.fr/de/map/dark-mode_297704#12 

is it possible to switch to this map?

### Steps to reproduce

Set mapUrl to 'https://tiles.wmflabs.org/bw-mapnik/${z}/${x}/${y}.png' 

![image](https://user-images.githubusercontent.com/71972934/195798654-b3e9a1ff-1782-4230-9abe-c3cf34d58a6f.png)

### config.js

```javascript
{
			module: "MMM-RAIN-MAP",
			position: "top_right",
			config: {
				animationSpeedMs: 400,
				colorScheme: 2,
				colorizeTime: true,
				defaultZoomLevel: 8,
				displayTime: true,
				displayTimeline: true,
				displayClockSymbol: true,
				displayHoursBeforeRain: -1,
				extraDelayLastFrameMs: 1000,
				extraDelayCurrentFrameMs: 0,
				markers: [
					{ lat: mylocation, lng: mylocation , color: "black" },
				],
				mapPositions: [
					{ lat: mylocation, lng: mylocation, zoom: 10, loops: 1 },
					{ lat: mylocation, lng: mylocation, zoom: 8, loops: 1 },
					{ lat: mylocation, lng: mylocation, zoom: 6, loops: 1 },

				],
				mapUrl: 'https://tiles.wmflabs.org/bw-mapnik/${z}/${x}/${y}.png',
				mapHeight: "420px", // must be a pixel value (no percent)
				mapWidth: "420px", // must be a pixel value (no percent)
				maxHistoryFrames: -1,
				maxForecastFrames: -1,
				substitudeModules: [],
				updateIntervalInSeconds: 300,
			}
		}
```

**Comment by geoek** [comment]
Any information or alternative url to obtain a dark map ? Thanks in advance !

**Comment by jalibu** [comment]
Hi @Rene1695,
hi @geoek,

the alternate mapUrl is still supported by this module. But unfortunately, more and more tile servers stop their free plan.
That's not something I can change either.
Of course, I'm grateful for tips if you find other tile servers that can be used for free and that can be shared with other users.

**Comment by jalibu** [comment]
Not a bug. Closed
