### ISSUE TITLE
Better clarify that a value of displayHoursBeforeRain > 0 only works with weather module

### ISSUE THREAD

**Issue by mike4192** [jalibu/MMM-RAIN-MAP#35]
### Platform

Rapsberry Pi 4

### MagicMirror Version

2.21.0

### Module Version

2.7.0, 53a4c283e1fae7906de0efe51f57f0f412d723a2

### Description

I think the readme could be clearer in describing that a value greater than 0 for `displayHoursBeforeRain` only works as intended if the module is used in conjunction with the `weather` module, but **not** with [MMM-OpenWeatherForecast](https://github.com/jclarke0000/MMM-OpenWeatherForecast).

The `weather` module publishes notifications `WEATHER_UPDATED` and `CURRENTWEATHER_TYPE`, while `MMM-OpeanWeatherForecast` only publishes `OPEANWEATHER_FORECAST_WEATHER_UPDATE`. [notificationReceived](https://github.com/jalibu/MMM-RAIN-MAP/blob/main/src/frontend/Frontend.ts#L303) either only handles `WEATHER_UPDATED` notification if `displayHoursBeforeRain > 0`, or handles both `OPENWEATHER_FORECAST_WEATHER_UPDATE` and `CURRENTWEATHER_TYPE` notifications if `displayHoursBeforeRain == 0`.

My experience shows that if a value for  `displayHoursBeforeRain > 0` is set in conjunction with `MMM-OpeanWeatherForecast`, then the rain map just always show.

### Steps to reproduce

1. Use MMM-OpenWeatherForecast as main weather module
2. Set MMM-RAIN-MAP config value for `displayHoursBeforeRain` to a value greater than 0
3. See that rain map always shows regardless if rain exists or not

### config.js

```javascript
{
			module: "MMM-RAIN-MAP",
			position: "lower_third",
			classes: 'xxx',
			config: {
				animationSpeedMs: 400,
				colorScheme: 1,
				colorizeTime: true,
				defaultZoomLevel: 8,
				displayTime: true,
				displayTimeline: true,
				displayClockSymbol: true,
				displayHoursBeforeRain: 0,
				extraDelayLastFrameMs: 1000,
				extraDelayCurrentFrameMs: 3000,
				markers: [
					{ lat: xxx, lng: xxx, color: "green" },
				],
				mapPositions: [
					{ lat: xxx, lng: xxx, zoom: 8, loops: 1 },
				],
				mapHeight: "420px", // must be a pixel value (no percent)
				mapWidth: "420px", // must be a pixel value (no percent)
				maxHistoryFrames: -1,
				maxForecastFrames: -1,
				substitudeModules: [],
				updateIntervalInSeconds: 300,
			}
		},
```

**Comment by jalibu** [comment]
Hi @mike4192,

thank you for the feedback :-)

Any proposal from your side how the readme can be improved?

**Comment by mike4192** [comment]
Re-reading it, I see now that your description is already pretty adequate. Somehow I missed the stated functionality. However I did still make an attempt at describing it even more explicitly. Perhaps something like below, I bolded my changes. You can feel free to incorporate, or I could open a PR with the change if you approve.

This option allows, to show or hide the map depending on the expected or current weather situation. The allowed values and options depend on your weather module which feeds MMM-RAIN-MAP with weather conditions under the hood.<br />**Both supported weather modules, listed below, support the basic options of** if set to `0` the map shows up on rain, and if set to `-1` the map is always displayed.<br/>**Supported modules and additional functionality**:<br/><ul><li>[weather](https://github.com/MichMich/MagicMirror/tree/master/modules/default/weather)<br>When used with type `hourly` allows you to use the weather forecast data and to display the map when rain is expected within a defined number of hours by setting a value greater `0`.</li><li>[MMM-OpenWeatherForecast](https://github.com/jclarke0000/MMM-OpenWeatherForecast)</li></ul>**Type:** `number` <br> **Default value:** `-1` |

**Comment by jalibu** [comment]
Thanks. I made some changes to the text, inspired by your proposal
