### ISSUE TITLE
no load map

### ISSUE THREAD

**Issue by chassain** [jalibu/MMM-RAIN-MAP#4]
hello Jalibu,

since 2 days i can run your module with mmm pages. I have only a little loading of the map on the iframe's corner..this module is running without other modules. i have modified some extradelays and position on the config but it's the same. It's a problem about loading.
Thanks

**Comment by chassain** [comment]
the only solution is to start with this module on the first page..not a problem but i wanted to understand

**Comment by c1olli** [comment]
Same problem for me  - there is no map displayed. I tried the OSM version.

**Comment by jalibu** [comment]
Hi @chassain and @c1olli 
do you still have that issue?

**Comment by c1olli** [comment]
I deleted the module, because I could not fix the Problem

**Comment by chassain** [comment]
> Salut @chassain et @ c1olli
> avez-vous toujours ce problème ?

it's ok in first page with mmm page for me
