### ISSUE TITLE
Here's a super easy way to make the map dark, like dark mode.

### ISSUE THREAD

**Issue by Milkysunshine** [jalibu/MMM-RAIN-MAP#41]
I found the white map such an eye sore on an otherwise dark themed MagicMirror setup. After some research and experimenting, It is actually super simple to make the map dark. 

Edit the custom.css file in MagicMirror/css/

Add this at the bottom. 

```
.leaflet-tile-pane {
  filter: invert(100%) hue-rotate(180deg);
}
```
Save file, and restart magic mirror. 

Enjoy your dark map.

**Comment by jalibu** [comment]
Hi @Milkysunshine 

thank you for sharing! I think I will make a configuration feature out of this

**Comment by Milkysunshine** [comment]
> Hi @Milkysunshine
> 
> thank you for sharing! I think I will make a configuration feature out of this

No worries! Thanks for making MagicMirror so much more useful with this module.

**Comment by jalibu** [comment]
-> official support

**Comment by Milkysunshine** [comment]
Thanks for adding that. Since there is actually heavy rain in the area, I'm noticing that the radar colors are also being adjusted. 
Is it possible to add a css class to only the map tiles (mapUrl), and invert only that?

**Comment by jalibu** [comment]
done

**Comment by Milkysunshine** [comment]
Looks perfect. Cheers.
