### ISSUE TITLE
Throws this error and map looks weird

### ISSUE THREAD

**Issue by ghost** [jalibu/MMM-RAIN-MAP#5]
:8080/modules/MMM-RAIN-MAP/utils.js:147 Uncaught TypeError: Cannot read property 'overlayMapTypes' of null
    at Function.clearLayers (:8080/modules/MMM-RAIN-MAP/utils.js:147)
    at XMLHttpRequest.apiRequest.onload (:8080/modules/MMM-RAIN-MAP//MMM-RAIN-MAP.js:92)

**Comment by JoshuaShelswell** [comment]
apparently it has something to do with hiding the time in the window

**Comment by JoshuaShelswell** [comment]
fixed it, changed it to pop instead of clear

**Comment by JoshuaShelswell** [comment]
tried a few things, nothing worked

**Comment by JoshuaShelswell** [comment]
[https://i.imgur.com/Z9A6VUS.png](url)

**Comment by JoshuaShelswell** [comment]
<a href="https://imgur.com/qOdtpm5"><img src="https://i.imgur.com/qOdtpm5.png" title="source: imgur.com" /></a>

**Comment by JoshuaShelswell** [comment]
update - doesnt matter what size the window seems to be
