### ISSUE TITLE
zoomOutEach / zoomOutLevel

### ISSUE THREAD

**Issue by PC24PC24** [jalibu/MMM-RAIN-MAP#9]
Hi
zoomOutEach / zoomOutLevel do not work. what do I wrong?

               {
        module: "MMM-RAIN-MAP",
        position: "top_left",
        config: {
                animationSpeed: 600,
                displayClockSymbol: true,
                displayTime: true,
                extraDelayLastFrame: 2000,
                height: "340px",
                lat: 47.382,
                lng: 8.165,
                map: "OSM",
                osmMapUrl: "http://tile.memomaps.de/tilegen/${z}/${x}/${y}.png",
        //      osmMapUrl: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                mapTypeId: "terrain",
                markers: [
                { lat: 47.382622, lng: 8.165470, color: "red" }
                ],
                onlyOnRain: false,
                opacity: 0.65,
                timeFormat: 24,
                updateIntervalInSeconds: 300,
                width: "620px",
                zoom: 7.85,
                zoomOutEach: "3",
                zoomOutLevel: "2",
        }
},

**Comment by jalibu** [comment]
Remove the quotes from the values, that they are treated as numbers, not as strings.
